# Include after RuntimeCleanupPatch.cmake (and the independent queue patch).
find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(_continuous_tool "${CMAKE_CURRENT_LIST_DIR}/../tools/prepare_runtime_continuous.py")
set(_continuous_directory "${CMAKE_BINARY_DIR}/runtime-continuous")
set(_continuous_cleanup "${CMAKE_BINARY_DIR}/runtime-cleanup/threads.cpp")
set(_continuous_app_src "${CMAKE_CURRENT_LIST_DIR}/../src")
set(_continuous_inputs)
foreach(_name threads mesgqueue timer events)
    list(APPEND _continuous_inputs "${RUNTIME_ROOT}/ultramodern/src/${_name}.cpp")
endforeach()
set(_continuous_save_input "${RUNTIME_ROOT}/librecomp/src/pi.cpp")
set(_continuous_translation_input "${RUNTIME_ROOT}/librecomp/src/ultra_translation.cpp")
set(_continuous_dp_input "${RUNTIME_ROOT}/librecomp/src/dp.cpp")
list(APPEND _continuous_inputs "${_continuous_save_input}" "${_continuous_translation_input}" "${_continuous_dp_input}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_continuous_tool}" ${_continuous_inputs} "${_continuous_cleanup}")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${_continuous_tool}"
    --runtime "${RUNTIME_ROOT}" --cleanup-threads "${_continuous_cleanup}"
    --output-directory "${_continuous_directory}"
    RESULT_VARIABLE _continuous_result OUTPUT_VARIABLE _continuous_stdout ERROR_VARIABLE _continuous_stderr)
if(NOT _continuous_result EQUAL 0)
    message(FATAL_ERROR "Continuous overlay materialization failed: ${_continuous_stdout}${_continuous_stderr}")
endif()
add_custom_target(verify_runtime_continuous
    COMMAND "${Python3_EXECUTABLE}" "${_continuous_tool}"
        --runtime "${RUNTIME_ROOT}" --cleanup-threads "${_continuous_cleanup}"
        --output-directory "${_continuous_directory}" VERBATIM)
add_dependencies(verify_runtime_continuous verify_runtime_cleanup)
add_dependencies(ultramodern verify_runtime_continuous)
add_dependencies(librecomp verify_runtime_continuous)
get_target_property(_continuous_sources ultramodern SOURCES)
get_target_property(_continuous_source_dir ultramodern SOURCE_DIR)
set(_continuous_new_sources)
set(_continuous_replaced 0)
foreach(_source IN LISTS _continuous_sources)
    get_filename_component(_absolute "${_source}" ABSOLUTE BASE_DIR "${_continuous_source_dir}")
    if(_absolute STREQUAL _continuous_cleanup)
        list(APPEND _continuous_new_sources "${_continuous_directory}/threads.cpp")
        math(EXPR _continuous_replaced "${_continuous_replaced}+1")
    elseif(_absolute MATCHES "/ultramodern/src/(mesgqueue|timer|events)\\.cpp$")
        get_filename_component(_name "${_absolute}" NAME)
        list(APPEND _continuous_new_sources "${_continuous_directory}/${_name}")
        math(EXPR _continuous_replaced "${_continuous_replaced}+1")
    else()
        list(APPEND _continuous_new_sources "${_source}")
    endif()
endforeach()
if(NOT _continuous_replaced EQUAL 4)
    message(FATAL_ERROR "Expected 4 continuous source substitutions, got ${_continuous_replaced}")
endif()
list(APPEND _continuous_new_sources "${_continuous_app_src}/runtime_lifecycle.cpp" "${_continuous_app_src}/virtual_clock.cpp" "${_continuous_app_src}/camera_interpolation.cpp" "${_continuous_app_src}/model_interpolation.cpp")
set_property(TARGET ultramodern PROPERTY SOURCES "${_continuous_new_sources}")
target_include_directories(ultramodern PRIVATE "${_continuous_app_src}")
# Preserve target properties while overlaying opt-in save drain and unsupported yield.
get_target_property(_continuous_save_sources librecomp SOURCES)
get_target_property(_continuous_save_source_dir librecomp SOURCE_DIR)
set(_continuous_save_new_sources)
set(_continuous_save_replaced 0)
foreach(_source IN LISTS _continuous_save_sources)
    get_filename_component(_absolute "${_source}" ABSOLUTE BASE_DIR "${_continuous_save_source_dir}")
    if(_absolute STREQUAL _continuous_save_input)
        list(APPEND _continuous_save_new_sources "${_continuous_directory}/pi.cpp")
        math(EXPR _continuous_save_replaced "${_continuous_save_replaced}+1")
    elseif(_absolute STREQUAL _continuous_translation_input)
        list(APPEND _continuous_save_new_sources "${_continuous_directory}/ultra_translation.cpp")
        math(EXPR _continuous_save_replaced "${_continuous_save_replaced}+1")
    elseif(_absolute STREQUAL _continuous_dp_input)
        list(APPEND _continuous_save_new_sources "${_continuous_directory}/dp.cpp")
        math(EXPR _continuous_save_replaced "${_continuous_save_replaced}+1")
    else()
        list(APPEND _continuous_save_new_sources "${_source}")
    endif()
endforeach()
if(NOT _continuous_save_replaced EQUAL 3)
    message(FATAL_ERROR "Expected three continuous librecomp source substitutions, got ${_continuous_save_replaced}")
endif()
set_property(TARGET librecomp PROPERTY SOURCES "${_continuous_save_new_sources}")
target_include_directories(librecomp PRIVATE "${_continuous_app_src}")

add_executable(continuous_dp_freeze_test "${_continuous_app_src}/../tests/continuous_dp_freeze_test.cpp")
target_compile_definitions(continuous_dp_freeze_test PRIVATE TOOIE_EVENTS_RUNTIME_SOURCE="${_continuous_directory}/events.cpp")
target_include_directories(continuous_dp_freeze_test PRIVATE "${RUNTIME_ROOT}/thirdparty" "${RUNTIME_ROOT}/thirdparty/concurrentqueue")
target_link_libraries(continuous_dp_freeze_test PRIVATE TooieFoundation ${CMAKE_DL_LIBS})
add_dependencies(continuous_dp_freeze_test verify_runtime_continuous)
foreach(mode pre mid stop-pre stop-mid two parser-failure normal disabled status vi-unfreeze refreeze)
    add_test(NAME continuous_dp_freeze_${mode} COMMAND continuous_dp_freeze_test ${mode})
    set_tests_properties(continuous_dp_freeze_${mode} PROPERTIES TIMEOUT 10)
endforeach()

add_executable(continuous_unsupported_yield_test "${_continuous_app_src}/../tests/continuous_unsupported_yield_test.cpp")
target_link_libraries(continuous_unsupported_yield_test PRIVATE TooieFoundation)
add_dependencies(continuous_unsupported_yield_test verify_runtime_continuous)
foreach(mode same higher)
    add_test(NAME continuous_yield_${mode} COMMAND continuous_unsupported_yield_test ${mode})
    set_tests_properties(continuous_yield_${mode} PROPERTIES TIMEOUT 10)
endforeach()
if(CMAKE_BUILD_TYPE MATCHES "^(Release|RelWithDebInfo|MinSizeRel)$")
    add_test(NAME continuous_unsupported_yield_disabled COMMAND continuous_unsupported_yield_test disabled)
    set_tests_properties(continuous_unsupported_yield_disabled PROPERTIES TIMEOUT 10)
endif()
